application:
  port: 8000
  host: 0.0.0.0
  secret: "caipora"
  policy_vkey_file: "~/policy/policy.vkey"
  policy_skey_file: "~/policy/policy.skey"
node:
  environment: testnet
  magic_number: 1097911063